CREATE TABLE Person(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  hash VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Note(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  person_id INTEGER,
  FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE Shared(
  id SERIAL PRIMARY KEY,
  link VARCHAR(50) NOT NULL,
  person_id INTEGER,
  note_id INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (person_id) REFERENCES person (id),
  FOREIGN KEY (note_id) REFERENCES note (id)
);
